---
- name: Bastion host setup 
  hosts: localhost
  connection: local
  gather_facts: no 
  tasks: 
      - name: Import variable from vars
        include_vars:  vars/bastion_setup

      - name: Import VPC Output variables 
        include_vars: vars/