- hosts: localhost
  name: local
  gather_facts: no
  tasks:
        - name: create a new ec2 key pair, returns generated private key
          ec2_key:
                name: sample_keypair
                region: ap-south-1
          register: keyout

        - debug:
                var: keyout
        - name: store private key in file
          copy:
                content: "{{keyout.key.private_key}}"
                dest: ./sample_privkey.pem
          when: keyout.changed
