- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
      - name: Import VPC File
        include_vars:  vars/vpc_setup 
      
      - name: Create hkt_vpc
        ec2_vpc_net: 
          name: "{{vpc_name}}"
          cidr_block: "{{vpcCidr}}"
          region: "{{region}}"
          dns_support: yes
          dns_hostnames: yes
          tenancy: default
          state: "{{state}}"
        register: vpcout