# Author : Hitesh Talhilyani
- name: webapp stack setup 
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC Variable File
      include_vars:  vars/output_vars

    - name: Import EC2 Variable File
      include_vars:  vars/webappstack

    - name: Create Webapp EC2 Key 
      ec2_key:
              name: webappec2_keypair
              region: "{{region}}"
      register: webappkey_out

    - name: Save Webapp EC2 private key in ppk format
      copy:
              content: "{{webappkey_out.key.private_key}}"
              dest: "./webapp-key.ppk"
              mode: 0600
      when: webappkey_out.changed


    - name: Create Load Balancer Security Group 
      ec2_group:
              name: "{{webapplb-sg}}"
              description: Webapp Loadbalancer Security Group 
              vpc_id: "{{vpcid}}"
              region: "{{region}}"
              rules:
              - proto: tcp
                from_port: 80
                to_port: 80
                cidr_ip: 0.0.0.0/0
                rule_desc: allow port 80 from anywhere and within the security group
      register: lbsg_out

    - name: Create Webapp EC2  Security Group 
      ec2_group:
              name: "{{ webapp-sg }}"
              description: Webapp EC2 Security Group 
              vpc_id: "{{vpcid}}"
              region: "{{region}}"
              purge_rules: no
              rules:
              - proto: tcp
                from_port: 80
                to_port: 80
                group_id: "{{lbsg_out.group_id}}"
                rule_desc: allow port 80 from Elastic LB

              - proto: tcp
                from_port: 22
                to_port: 22
                group_id: "{{BastionSGid}}"
                rule_desc: allow port 22 from Elastic LB        
      register: ec2webappsg_out  

    - name: Update Webapp EC2  Security Group 
      ec2_group:
              name: "{{ webapp-sg }}"
              description: Allow all ports within the security group
              vpc_id: "{{vpcid}}"
              region: "{{region}}"
              purge_rules: no
              rules:
              - proto: all
                group_id: "{{ec2webappsg_out.group_id}}"
                rule_desc: allow all ports from Elastic LB



    
        

