# Author : Hitesh Talhilyani
- name: webapp stack setup 
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC Variable File
      include_vars:  vars/output_vars

    - name: Import EC2 Variable File
      include_vars:  vars/webappstack

    - name: Create Webapp EC2 Key 
      ec2_key:
              name: webappec2_keypair
              region: "{{region}}"
      register: webappkey_out

    - name: Save Webapp EC2 private key in ppk format
      copy:
              content: "{{webappkey_out.key.private_key}}"
              dest: "./webapp-key.ppk"
              mode: 0600
      when: webappkey_out.changed


    - name: Create Load Balancer Security Group 
      ec2_group:
              name: webappstack-lb
              description: Webapp Loadbalancer Security Group 
              vpc_id: "{{vpcid}}"
              region: "{{region}}"
              rules:
              - proto: tcp
                from_port: 80
                to_port: 80
                cidr_ip: 0.0.0.0/0
                rule_desc: allow port 80 from anywhere and within the security group
      register: lbsg_out

    - name: Create Webapp EC2  Security Group 
      ec2_group:
              name: ec2webappstack-sg
              description: Webapp EC2 Security Group 
              vpc_id: "{{vpcid}}"
              region: "{{region}}"
              purge_rules: no
              rules:
              - proto: tcp
                from_port: 80
                to_port: 80
                group_id: "{{lbsg_out.group_id}}"
                rule_desc: allow port 80 from Elastic LB

              - proto: tcp
                from_port: 22
                to_port: 22
                group_id: "{{BastionSGid}}"
                rule_desc: allow port 22 from Bastion Host      
      register: ec2webappsg_out  

    - name: Update Webapp EC2  Security Group 
      ec2_group:
              name: ec2webappstack-sg
              description: Webapp EC2 Security Group
              vpc_id: "{{vpcid}}"
              region: "{{region}}"
              purge_rules: no
              rules:
              - proto: all
                group_id: "{{ec2webappsg_out.group_id}}"
                rule_desc: allow all ports within in the security group

      - name: Create web01 NGINX Host in Private Subnet
        ec2:
          key_name: "webappec2_keypair"
          region: "{{region}}"
          instance_type: t2.micro
          image: "{{nginx_ami}}"
          wait: yes
          wait_timeout: 300
          vpc_subnet_id: "{{privsub1id}}"
          instance_tags:
            Name: "web01"
            Project: Webapp
            Owner: Hitesh
            Environment: Testing
          exact_count: 1
          count_tag: 
            Name: "web01"
            Project: Webapp
            Owner: Hitesh
            Environment: Testing
          group_id: "{{ec2webappsg_out.group_id}}"
        register: web01_out
    
    - name: Create Tomcat App01 Host in Private Subnet
      ec2:
          key_name: "webappec2_keypair"
          region: "{{region}}"
          instance_type: t2.micro
          image: "{{tomcat_ami}}"
          wait: yes
          wait_timeout: 300
          vpc_subnet_id: "{{privsub2id}}"
          instance_tags:
            Name: "app01"
            Project: Webapp
            Owner: Hitesh
            Environment: Testing
          exact_count: 1
          count_tag: 
            Name: "app01"
            Project: Webapp
            Owner: Hitesh
            Environment: Testing
          group_id: "{{ec2webappsg_out.group_id}}"
        register: app01_out

    - name: Create Memcache Host in Private Subnet
      ec2:
          key_name: "webappec2_keypair"
          region: "{{region}}"
          instance_type: t2.micro
          image: "{{memcache_ami}}"
          wait: yes
          wait_timeout: 300
          vpc_subnet_id: "{{privsub3id}}"
          instance_tags:
            Name: "mc01"
            Project: Webapp
            Owner: Hitesh
            Environment: Testing
          exact_count: 1
          count_tag: 
            Name: "mc01"
            Project: Webapp
            Owner: Hitesh
            Environment: Testing
          group_id: "{{ec2webappsg_out.group_id}}"
        register: mc01_out

    - name: Create RabbitMQ Host in Private Subnet
      ec2:
          key_name: "webappec2_keypair"
          region: "{{region}}"
          instance_type: t2.micro
          image: "{{rmq_ami}}"
          wait: yes
          wait_timeout: 300
          vpc_subnet_id: "{{privsub1id}}"
          instance_tags:
            Name: "rmq01"
            Project: Webapp
            Owner: Hitesh
            Environment: Testing
          exact_count: 1
          count_tag: 
            Name: "rmq01"
            Project: Webapp
            Owner: Hitesh
            Environment: Testing
          group_id: "{{ec2webappsg_out.group_id}}"
        register: rmq01_out

    - name: Create MYSQL Host in Private Subnet
      ec2:
          key_name: "webappec2_keypair"
          region: "{{region}}"
          instance_type: t2.micro
          image: "{{mysql_ami}}"
          wait: yes
          wait_timeout: 300
          vpc_subnet_id: "{{privsub2id}}"
          instance_tags:
            Name: "mysql01"
            Project: Webapp
            Owner: Hitesh
            Environment: Testing
          exact_count: 1
          count_tag: 
            Name: "mysql01"
            Project: Webapp
            Owner: Hitesh
            Environment: Testing
          group_id: "{{ec2webappsg_out.group_id}}"
        register: mysql01_out

    - name: Print Output of MYSQL EC2
      debug: 
        var: mysql01_out





    
        

