#Author: Hitesh Talhilyani
---
- name: Setup tomcat8 & Deploy Artifact 
  hosts: appsrvgrp
  #gather_facts: no 
  vars: 
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"
    tom_url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.37/bin/apache-tomcat-8.5.37.tar.gz

  tasks: 
    - name: Install JDK on Ubuntu 
      apt: 
        name: openjdk-8-jdk
        state: present
        update_cache: yes

    - name: Download Tomcat tar Ball/Binaries
      get_url:
        url: "{{tom_url}}"
        dest: /tmp/tomcat-8.tar.gz

    - name: Add tomcat user
      user: 
        name: tomcat
        group: tomcat
        shell: /bin/nologin
        home: /usr/local/tomcat8


    - file:
        path: /tmp/tomcat8
        state: directory

    - name: Extract tomcat 
      unarchive:
        src: /tmp/tomcat-8.tar.gz
        dest: /tmp/tomcat8/
        remote_src: yes
        list_files: yes
      register: unarchive_info


    - debug:
        msg: "{{unarchive_info.files[0].split('/')[0]}}/"

    - name: Synchronize /tmp/tomcat8/tomcat_cont /usr/local/tomcat8
      synchronize:
        src: "/tmp/tomcat8/{{unarchive_info.files[0].split('/')[0]}}/"
        dest: /usr/local/tomcat8
      delegate_to: "{{ inventory_hostname }}"

    - name: Change ownership of /usr/local/tomcat8
      file: 
        path: /usr/local/tomcat8
        owner: tomcat
        group: tomcat
        recurse: yes
    
    - name: Setup tomat SVC file on ubuntu 
      template: 
        src:  templates/tomcat8-ubuntu-svcfile.j2
        dest: /etc/systemd/system/tomcat8.service
        mode: "a+x"

    - name: Reload Systemd configuration 
      systemd: 
        daemon_reload: yes
    
    - name: Start and Enable Tomcat SVC
      service: 
        name: tomcat8
        state: started
        enabled: yes
      tags:
        - svc

    - stat:
        path: /usr/local/tomcat8/webapps/ROOT
      register: artifact_stat
      tags:
        - deploy

    - name: Stop Tomcat SVC
      service: 
        name: tomcat8
        state: stopped
      tags: 
        - deploy

    - name: Try Artifact Backup and Deploy
      block: 
        - name: Archive Root Directory with timestamp 
          archive: 
            path: /usr/local/tomcat8/webapps/ROOT
            dest: /opt/ROOT_{{timestamp}}.tgz"
          when: artifact_stat.stat.exists
          register: archive_info
          tags:
            - deploy

        - name: copy ROOT dir with old_ROOT name
          shell: cp -r ROOT old_ROOT
          args: 
            chdir: /usr/local/tomcat/webapps/

        - name: Delete current Artifact
          file: 
            path: "{{item}}"
            state: absent
          when: archive_info.changed
          loop:
            - /usr/local/tomcat8/webapps/ROOT
            - /usr/local/tomcate/webapps/ROOT.war
          tags:
            - deploy

        - name: Try deploy artifact else restore from previous old_ROOT
          block:
            - name: Deploy webapp artifact
              copy: 
                src: files/ROOT.war
                dest: /usr/local/tomcat8/webapps/ROOT.war
              register: deploy_info
              tags:
                - deploy
          rescue:
            - shell: cp -r old_ROOT ROOT
              args:
                chdir: /usr/local/tomcat8/webapps

      rescue:
        - name: start tomcate svc
          service:  
            name: tomcat
            state: started

      - name: If Deployment Successfull, Restart the service
        service:
          name: tomcat
          start: started
        when: deploy_info.changed
        tags:
          - deploy
      
      - name: Wait Until ROOT.war is extracted to ROOT Directory
        wait_for:
          path: /usr/local/tomcat8/webapp/ROOT
        tags:
          - deploy

      - name: Deploy Web configuration file 
        template:
          src: templates/application.j2
          dest: /usr/local/tomcat8/webapps/ROOT/WEB-INF/classes/application.properties
          force: yes
        notify:
          - Restart Tomcat
        tags:
          - deploy

  handlers:
    name: Restart Tomcat
    service:
      name: tomcat
      state: restarted


