#Author: Hitesh Talhilyani
---
- name: Install Memcache, Start and Enable SVC
  hosts: mcsrvgrp
  gather_facts: no 
  tasks: 
    - name: Install memcache
      apt:
        name: memcache
        state: present
        update_cache: yes
        cache_valid_time: 86400
      tags:
        - package
    
    - name: Start and Enable Service
      service:
        name: memcached
        state: started
        enabled: yes
      tags:
        - svc

    - name: Enable remote login to memcache
      lineinfile: 
        path: /etc/memcached.conf
        regexp: '^-l'
        line: '-l 0.0.0.0'
        backup: yes
      notify:
        - Restart memcache
      tags:
        - conf
    
    handlers:
      - Restart memcache
        service:  
          name: memcached
          state: restarted
          

