#Author: Hitesh Talhilyani
---
- name: Setup NGINX  and start the service
  hosts: websrvgrp
  gather_facts: no 
  tasks: 
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
        cache_valid_time: 86400
      tags:
        - package
    
    - name: Start and Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - svc

    - name: Disable Nginx default website
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      tags:
        - conf

    - name: Deploy web config file
      template:
        src: templates/nginxwebapp.j2
        dest: /etc/nginx/sites-available/vproapp
      tags:
        - conf
    
    - name: Enable vproapp website
      file: 
        src:  /etc/nginx/sites-available/vproapp
        dest: /etc/nginx/sites-enabled/vproapp
        state: link 
      notify:
        - Restart Nginx
      tags:   
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service: 
        name: nginx
        state: restarted
